### ISSUE TITLE
CosmicMutantExportCensus.tsv does not contain FATHMM columns

### ISSUE THREAD

**Issue by DSchreyer** [elyadlezmi/RNA2CM#4]
The last step `findCancerMutations` finishes with an error due to the missing columns in the CosmicMutantExportCensus.tsv file. 

Error:
```Command error:
  INFO:    Converting SIF file to temporary sandbox...
  Traceback (most recent call last):
    File ".command.sh", line 14, in <module>
      mutations = mutations[['Tier','GENOMIC_MUTATION_ID', 'Mutation AA', 'Mutation Description', 'FATHMM prediction','FATHMM score']]
    File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3030, in __getitem__
      indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
    File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
      self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
    File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
      raise KeyError(f"{not_found} not in index")
  KeyError: "['FATHMM score', 'FATHMM prediction'] not in index"
  INFO:    Cleaning up image...
```

Did the version change?

**Comment by DSchreyer** [comment]
Version v96 does not contain FATHMM information, but v95 does. To download v95 - https://cancer.sanger.ac.uk/cosmic/file_download/GRCh38/cosmic/v95/CosmicMutantExportCensus.tsv.gz
